// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect"

type Snowflake struct {
	AccountURL        string `json:"account-url" env:"BATON_ACCOUNT_URL" validate:"required"`
	AccountIdentifier string `json:"account-identifier" env:"BATON_ACCOUNT_IDENTIFIER" validate:"required"`
	UserIdentifier    string `json:"user-identifier" env:"BATON_USER_IDENTIFIER" validate:"required"`
	PrivateKeyPath    string `json:"private-key-path,omitempty" env:"BATON_PRIVATE_KEY_PATH"`
	PrivateKey        string `json:"private-key,omitempty" env:"BATON_PRIVATE_KEY"`
	SyncSecrets       bool   `json:"sync-secrets" env:"BATON_SYNC_SECRETS"`
}

var typeNameSnowflake = reflect.TypeOf((*Snowflake)(nil)).Elem().Name()

func (c *Snowflake) GetConnectorTypeName() string {
	return typeNameSnowflake
}
